### ISSUE TITLE
Bug Report: Error When Using Beam Splitters Without a Defined Filter

### ISSUE THREAD

**Issue by ramezquitao** [cihologramas/pyoptools#173]
**Description**

When running an older code version that utilizes beam splitters without a defined filter, the following error occurs:

```
18:20:11  Running the Python command 'btnPropagate' failed:
Traceback (most recent call last):
  File "/home/richi/.local/share/FreeCAD/Mod/pyOpToolsWorkbench/freecad/pyoptools/pyOpToolsWB/propagate.py", line 36, in Activated
    PropagatePart(myObj)
  File "/home/richi/.local/share/FreeCAD/Mod/pyOpToolsWorkbench/freecad/pyoptools/pyOpToolsWB/propagate.py", line 63, in __init__
    self.S, rays = getActiveSystem()
                   ^^^^^^^^^^^^^^^^^
  File "/home/richi/.local/share/FreeCAD/Mod/pyOpToolsWorkbench/freecad/pyoptools/pyOpToolsWB/pyoptoolshelpers.py", line 81, in getActiveSystem
    e = obj.Proxy.pyoptools_repr(obj)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/richi/.local/share/FreeCAD/Mod/pyOpToolsWorkbench/freecad/pyoptools/pyOpToolsWB/roundmirror.py", line 95, in pyoptools_repr
    rm = comp_lib.RoundMirror(
         ^^^^^^^^^^^^^^^^^^^^^
  File "/home/richi/.local/share/FreeCAD/AdditionalPythonPackages/py311/pyoptools/raytrace/_comp_lib/mirror.py", line 39, in __init__
    __a_surf = Plane(
               ^^^^^^
  File "pyoptools/raytrace/surface/plane.pyx", line 40, in pyoptools.raytrace.surface.plane.Plane.__init__
  File "pyoptools/raytrace/surface/surface.pyx", line 116, in pyoptools.raytrace.surface.surface.Surface.__init__


Invalid filter type: no_filter
```

Steps to Reproduce

    Use a codebase where beam splitters lack a defined filter.
    Attempt to run propagation using the btnPropagate command.

Expected Behavior

The software should handle undefined filters gracefully, either by:

    Applying a default filter, or
    Raising a user-friendly warning or exception indicating the missing filter.

Actual Behavior

The code raises an unhandled exception with the message Invalid filter type: no_filter, causing the propagation process to fail.
Environment

    FreeCAD Version: 1.0.0
    pyOpTools Workbench Version: Latest
    Operating System: Linux
    Python Version: 3.11

**Comment by shunyinghuang** [comment]
Revise "no_filter" as "nofilter" will be worked.
