### ISSUE TITLE
all dots in extensions paths are converted to slashes

### ISSUE THREAD

**Issue by ederag** [cihologramas/pyoptools#55]
Trying to install b7ace275c49485d6e9040e04171164658a55f78d in a virtual environment yields
```python
Traceback (most recent call last):
  File "setup.py", line 137, in <module>
    ext_modules=cythonize(extensions),
  File "/home/ederag/share/prog/python/pyoptools/env/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 966, in cythonize
    aliases=aliases)
  File "/home/ederag/share/prog/python/pyoptools/env/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 810, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/home/ederag/share/prog/python/pyoptools/env/lib64/python3.6/site-packages/Cython/Build/Dependencies.py", line 109, in nonempty
    raise ValueError(error_msg)
ValueError: 'env/lib/python3/6/site-packages/Cython/Runtime/refnanny.pyx' doesn't match any files
```
The reason is that slashes are converted to dots by
https://github.com/cihologramas/pyoptools/blob/b7ace275c49485d6e9040e04171164658a55f78d/setup.py#L36-L40

and then all dots (including the dot in `/python3.6/`) are converted back to slashes
https://github.com/cihologramas/pyoptools/blob/b7ace275c49485d6e9040e04171164658a55f78d/setup.py#L59-L60

Is there any reason for not working directly with paths,
and converting path to name in `makeExtension` ?

**Comment by ederag** [comment]
Side note: the issue revealed itself because I created the `env` directory inside the project,
following this [primer](https://realpython.com/python-virtual-environments-a-primer/).

Changing this line
https://github.com/cihologramas/pyoptools/blob/b7ace275c49485d6e9040e04171164658a55f78d/setup.py#L109
to `extNames = scandir("./pyoptools/")` allows to build,
yet the installation ends with
```bash
writing top-level names to pyoptools.egg-info/top_level.txt
writing manifest file 'pyoptools.egg-info/SOURCES.txt'
error: package directory 'env/lib/python3/6/site-packages/pkg_resources' does not exist
```

**Comment by ramezquitao** [comment]
Right now I don't exactly remember the reason I did that, but I think it has to be on how setup needs to receive the extension names. 

Anyway, the idea is that setup will look automatically for all the extensions that have to be built, so if you put something else inside pyoptools source code directory, this functions will get confused. 

I just tested installing the virtualenv in a different directory outside pyoptools, and everything worked as expected (kind of).

The issues I found is that the scipy version referred in the requirements file did no install from pip. I did install scipy==1.1 , other problem is that   pythreejs is not in requirements.txt , and finally that jupyter is not in the requirements either.

Installing this packages in your virtualenv solves the problem.

As soon as I correct requirements.txt I will close this issue.

**Comment by ederag** [comment]
Then the installation instructions could mention 
to avoid putting the virtual environment inside the repository ?

> The issues I found is that the scipy version referred in the requirements file did no install from pip

That is probably because numpy has to be installed first.
Unfortunately, with the latest scipy,
```python
(pyoptools) > python3 -c "from pyoptools.all import *"
...
    from scipy.misc import toimage
ImportError: cannot import name 'toimage'
```
and with the latest matplotlib,
```python
(pyoptools) > python3 -c "from pyoptools.all import *"
    from pylab import griddata, meshgrid
ImportError: cannot import name 'griddata'
```
So for now, these dependencies have to remain constrained.

Using the updated `requirements.txt` proposed in PR #56, it works:

```bash
> venvwrapper -o pyoptools
(pyoptools) > export LAPACK=/usr/local/gcc-8.1.0_binutils-2.30_isl/lib64/libopenblas.so
(pyoptools) > export BLAS=/usr/local/gcc-8.1.0_binutils-2.30_isl/lib64/libopenblas.so
(pyoptools) > pip install -r requirements.txt
(pyoptools) > pip install --upgrade .
```

`matplotlib` looks for a Qt version, but these do not work inside a `venv`,
so to access the pyqt5 already installed globally,
```bash
pip install vext.pyqt5
```
Then launching the jupyter interface:
```bash
(pyoptools) > ipyoptools
```
In the jupyter that appear, I had to change the kernel from python2 to python3.

Then the tutorial worked fine, that looks very good, congratulations !
